version: '3.7'

networks:
  bridge:
    external:
      name: ${NETWORKS}

services:
  student:
    image: nginx:alpine
    container_name: 0verStudent
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist/:/usr/share/nginx/html/
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.student.entrypoints=websecure"
      - "traefik.http.routers.student.tls.certresolver=lets-encr"
      - "traefik.http.routers.student.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.student.tls.options=default"
      - "traefik.http.routers.student.middlewares=secure-headers@file,traefik-compress@file"