version: '3'

networks:
  0versea:
    external: true
    name: 0versea

services:
  nginx:
    image: nginx:alpine
    container_name: 0verStudent
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./app/dist/:/usr/share/nginx/html/

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=lets-encr"
      - "traefik.http.routers.nginx.rule=Host(`test.overseas.imoncloud.com`)"
